# Generated by Django 6.0.8 on 2026-08-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-id'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
    ]
